// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-16.glb -T 
Files: macbook-16.glb [639.28KB] > /Users/rithwick/Product/gsap_macbook_landing/public/models/macbook-16-transformed.glb [629.72KB] (1%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import React, { useEffect } from 'react'
import { useGLTF, useVideoTexture, Html } from '@react-three/drei'
import useMacbookStore from '../../store';
import { noChangeParts } from '../../constants';
import { Color, SRGBColorSpace } from 'three';


export default function MacbookModel16(props: any) {
  const { nodes, materials, scene } = useGLTF('/models/macbook-16-transformed.glb') as any;
  const { color, texture: textureUrl } = useMacbookStore();

  const texture = useVideoTexture(textureUrl, { crossOrigin: 'Anonymous', muted: true, loop: true, playsInline: true });
  texture.colorSpace = SRGBColorSpace;
  texture.needsUpdate = true;

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    })
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      {/* LAYER 5: BOTTOM CHASSIS */}
      <group name="layer_chassis">
        <Html position={[0, -2, 5]} center transform>
          <div className="explode-label opacity-0 border-2 border-blue bg-black px-4 py-2 font-bold text-blue tracking-widest uppercase text-xs whitespace-nowrap shadow-[4px_4px_0px_#CCFF00]">
            Aluminum Shell
          </div>
        </Html>
        <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      {/* LAYER 4: BATTERY & COOLING */}
      <group name="layer_battery">
        <Html position={[0, -2, -5]} center transform>
          <div className="explode-label opacity-0 border-2 border-blue bg-black px-4 py-2 font-bold text-blue tracking-widest uppercase text-xs whitespace-nowrap shadow-[4px_4px_0px_#CCFF00]">
            Battery & Cooling
          </div>
        </Html>
        <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      {/* LAYER 3: LOGIC BOARD */}
      <group name="layer_logic">
        <Html position={[0, 0, 0]} center transform>
          <div className="explode-label opacity-0 border-2 border-blue bg-black px-4 py-2 font-bold text-blue tracking-widest uppercase text-xs whitespace-nowrap shadow-[4px_4px_0px_#CCFF00]">
            M3 Pro Logic Board
          </div>
        </Html>
        <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      {/* LAYER 2: KEYBOARD DECK */}
      <group name="layer_keyboard">
        <Html position={[0, 2, 5]} center transform>
          <div className="explode-label opacity-0 border-2 border-blue bg-black px-4 py-2 font-bold text-blue tracking-widest uppercase text-xs whitespace-nowrap shadow-[4px_4px_0px_#CCFF00]">
            Keyboard & Trackpad
          </div>
        </Html>
        <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      {/* LAYER 1: SCREEN */}
      <group name="layer_screen">
        <Html position={[0, -15, -23]} center transform>
          <div className="explode-label opacity-0 border-2 border-blue bg-black px-4 py-2 font-bold text-blue tracking-widest uppercase text-xs whitespace-nowrap shadow-[4px_4px_0px_#CCFF00]">
            Liquid Retina XDR
          </div>
        </Html>
        <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.sfCQkHOWyrsLmor} rotation={[Math.PI / 2, 0, 0]} >
          <meshBasicMaterial map={texture} />
        </mesh>
        <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/macbook-16-transformed.glb')
